install ack
install aircrack-ng
install bash
install bash-completion
install binutils
install binwalk
install brew-cask-completion
install cairo
install cifer
install homebrew/php/composer
install coreutils
install dark-mode
install diff-so-fancy
install elm
install exiftool
install fcgi
install fcrackzip
install findutils
install fish
install foremost
install gcc
install git
install git-flow-avh
install git-ftp
install git-lfs
install gnu-sed
install gnupg2
install graphicsmagick
install homebrew/dupes/grep
install haskell-stack
install htop
install hub
install imagemagick
install homebrew/dupes/less
install libidn
install libyaml
install little-cms2
install lua
install lynx
install macvim
install mongodb
install moreutils
install mysql
install narwhal
install netpbm
install nginx
install nmap
install homebrew/science/opencv
install homebrew/dupes/openssh
install pandoc
install homebrew/php/php70-mongodb
install homebrew/php/php70-phalcon
install pigz
install pngcheck
install pv
install python
install python3
install rabbitmq
install reattach-to-user-namespace
install rename
install rhino
install ringojs
install homebrew/dupes/screen
install bramstein/webfonttools/sfnt2woff
install bramstein/webfonttools/sfnt2woff-zopfli
install speedtest_cli
install sqlmap
install ssh-copy-id
install subversion
install tcpflow
install tcpreplay
install tcptrace
install the_silver_searcher
install tmux
install tree
install ucspi-tcp
install watchman
install webkit2png
install wget
install bramstein/webfonttools/woff2
install yarn
install youtube-dl
install homebrew/dupes/zlib
install zopfli
cask 1password
cask adobe-reader
cask alfred
cask android-file-transfer
cask android-studio
cask appcleaner
cask brave
cask dash
cask divvy
cask dropbox
cask firefox
cask gitify
cask google-chrome
cask google-chrome-canary
cask imagealpha
cask imageoptim
cask iterm2
cask java
cask libreoffice
cask pgadmin4
cask postman
cask robomongo
cask safari-technology-preview
cask sketch
cask skype
cask slack
cask spotify
cask sublime-text
cask transmission
cask transmit
cask tunnelblick
cask unrarx
cask virtualbox
cask vlc
